name: Linter

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop
